[package]
name = "minio-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true


[dependencies]
syn = "2.0.53"
proc-macro2 = "1.0.37"
quote = "1.0.18"
darling = "0.20.8"
darling_core = "0.20.8"
uuid = { version = "1.17.0", features = ["v4"] }